#!/bin/sh

## Libs
TMP_DIR=/tmp/${0##*/}.jslib
JQM_HOME=${TMP_DIR}/js/jqm
JQ_HOME=${TMP_DIR}/js/jq
TARGET_DIR=www

## jq Library
JQUERY=${JQ_HOME}/jquery-*.min.js
JQM=${JQM_HOME}/jquery.mobile-*.min.js
JQM_CSS=${JQM_HOME}/jquery.mobile-*.min.css
JQM_IMAGES=${JQM_HOME}/images

# CDN
CDN_JQM_CSS=http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css
CDN_JQM=http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js
CDN_JQUERY=http://code.jquery.com/jquery-1.9.1.min.js
CDN_JQM_ZIP=http://jquerymobile.com/resources/download/jquery.mobile-1.3.2.zip
##

function _echo (){
  _d=`date`
  echo "[${_d}] $@"
}
function _cmd (){
  if $@ ; then
    _echo Success: $@
  else
    _echo Failed: $@
    exit 1
  fi
}

WORK_DIR=${PWD}

if [ ! -d ${TMP_DIR} ] ;then
  _echo "Create template dir. ${TMP_DIR}"
  _cmd mkdir -p ${TMP_DIR}
fi

if [ ! -d ${JQM_HOME} ] ;then
  _cmd mkdir -p ${JQM_HOME}
fi

if [ ! -f ${JQM} ] ;then
  _cmd wget ${CDN_JQM_ZIP} -P ${JQM_HOME}
  _cmd cd ${JQM_HOME} ; unzip jquery.mobile-*.zip
fi

if [ ! -d ${JQ_HOME} ] ; then
  _cmd mkdir -p ${JQ_HOME}
fi

if [ ! -f ${JQUERY} ] ;then
  _cmd wget ${CDN_JQUERY} -P ${JQ_HOME}
fi

_echo "Library ... ok"
_echo ${JQUERY}
_echo ${JQM}
_echo ${JQM_CSS}
_echo ${JQM_IMAGES}

JQUERY=`echo ${JQUERY}`
JQM=`echo ${JQM}`
JQM_CSS=`echo ${JQM_CSS}`
JQM_IMAGES=`echo ${JQM_IMAGES}`

_cmd cd ${WORK_DIR}
_echo "copy target dir www ..."
if [ ! -d ${TARGET_DIR} ] ; then
  _echo "Failed: You need to execute this command in PhoneGap project directory."
  exit 1
fi

_echo "Copying jq libraries to phonegap project."

_cmd cp ${JQUERY} ${TARGET_DIR}/js
_cmd cp ${JQM} ${TARGET_DIR}/js
_cmd cp ${JQM_CSS} ${TARGET_DIR}/css
_cmd cp -r ${JQM_IMAGES} ${TARGET_DIR}/css

_echo "Insert script tag to index.html in your project."

LINE_OF_CSS='        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/'${JQM_CSS##*/}'\" />'
LINE_OF_JQ='        <script src=\"js/'${JQUERY##*/}'\"></script>'
LINE_OF_JQM='        <script src=\"js/'${JQM##*/}'\"></script>'

if grep "${LINE_OF_JQM}" www/index.html > /dev/null ; then
  _echo "Already inserted script tags. Nothing to do." 
  exit 0
fi

INSERT_LINE="${LINE_OF_CSS}\\\n${LINE_OF_JQ}\\\n${LINE_OF_JQM}"

TMP_AWK_FILE=${0##*/}.tmp.awk
echo '$1~/<\/head>/{' > ${TMP_AWK_FILE}
echo "print \"${INSERT_LINE}\\\n\"\$0 }" >> ${TMP_AWK_FILE} 
echo "{print}" >> ${TMP_AWK_FILE}

TMP_WWW_INDEX_HTML=/tmp/${0##*/}.tmp.www.index.html
_echo "exec cat www/index.html | awk -f ${TMP_AWK_FILE} > ${TMP_WWW_INDEX_HTML}"
cat www/index.html | awk -f ${TMP_AWK_FILE} > ${TMP_WWW_INDEX_HTML}
mv -f ${TMP_WWW_INDEX_HTML} www/index.html
rm -f ${TMP_AWK_FILE}


_echo "finish."
